name: Provision t2.micro EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: 'App Server'
        type: string

jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
   
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-2
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_INSTANCE }}" > ~/.ssh/app-ssh-key.pem
          chmod 600 ~/.ssh/app-ssh-key.pem
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_ec2_name: "${{ github.event.inputs.ec2-name }}"
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
